#!/usr/bin/env tsx
// Generates a fixed set of realistic one-shot bonus boards per qualifier
// tier, for embedding as static data (src/engine/bonusOpponentSamples.ts).
// Run with: npx tsx scripts/compute-bonus-samples.ts > /tmp/bonus-samples-out.txt
//
// Why this exists: mc.ts's rollout() needs to score a side-game candidate
// against an INVISIBLE bonus-eligible opponent (info-set hygiene — their
// board is never revealed during play, but they're still scored against at
// showdown). Averaging just their royalties (the old AVG_BONUS_ROYALTY
// approach) silently assumes the row-score half of the comparison is a wash
// (0), which is wrong: bonus boards are built from a bigger 13-15 card pool
// specifically to maximize royalties, so they also tend to win rows more
// often than a neutral assumption suggests. Calling bestBonusBoard() live
// inside a rollout to get a real opponent board is not an option — it's an
// exhaustive search that costs ~7.5M evaluations for a 15-card (AA_OR_TRIPS)
// hand, and rollout() runs thousands of times per coaching decision.
//
// The fix: do the expensive part (solving a freshly dealt random hand —
// exactly what the game's own "fresh reshuffled deck per bonus round" rule
// describes) ONCE per sample, offline, and bake a modest set of resulting
// boards in as static data. At rollout time we just pick one at random and
// score it with the already-cheap scorePair() — no search, just a direct
// hand comparison — so this is candidate-sensitive (the actor's REAL board
// this rollout gets compared against a REAL bonus board) without costing
// anything live.
//
// BOOTSTRAP NOTE: this regenerates BONUS_OPPONENT_SAMPLES using
// solveBonusVsOpponents (the kicker-aware solver, generic field — see
// bonusOpponentScoring.ts) rather than the plain bestBonusBoard. That
// solver's generic field is itself built from the CURRENT on-disk
// BONUS_OPPONENT_SAMPLES/SIDE_GAME_SAMPLES (loaded once at process start,
// before this script overwrites anything) — so running this regenerates the
// pool to be self-consistent with the upgraded solver: what a rational
// opponent using our best algorithm actually produces, rather than what the
// old kicker-blind first-tie-wins bestBonusBoard happened to produce.

import { solveBonusVsOpponents } from '../src/engine/bonusOpponentScoring'
import { bonusDealCount } from '../src/engine/rules'
import { Deck } from '../src/engine/deck'
import type { Board, BonusQualifier, Card } from '../src/engine/types'

function mulberry32(seed: number): () => number {
  let s = seed >>> 0
  return () => {
    s = (s + 0x6D2B79F5) >>> 0
    let t = s
    t = Math.imul(t ^ (t >>> 15), t | 1)
    t = (t ^ (t + Math.imul(t ^ (t >>> 7), t | 61))) >>> 0
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

const rng = mulberry32(20260824)

const TIERS: readonly BonusQualifier[] = ['QQ', 'KK', 'AA_OR_TRIPS']
const DISCARDS: Record<BonusQualifier, number> = { QQ: 0, KK: 1, AA_OR_TRIPS: 2 }
// 1000/tier — up from an earlier 800/800/450 pass (which was itself checked
// for convergence against the independently-computed AVG_BONUS_ROYALTY
// reference constants and bumped up after AA_OR_TRIPS's original 150-sample
// pool showed a ~7% mean gap with a half-split SE around 0.7 — too much
// noise for the tier with the highest stakes). solveBonusVsOpponents is
// substantially more expensive per sample than plain bestBonusBoard (it
// scores every royalty-tied candidate against full opponent pools), so this
// run will take meaningfully longer than the earlier bestBonusBoard-only
// passes — run in the background.
const SAMPLE_COUNTS: Record<BonusQualifier, number> = { QQ: 1000, KK: 1000, AA_OR_TRIPS: 1000 }

const RANK_CHAR: Record<number, string> = {
  2: '2', 3: '3', 4: '4', 5: '5', 6: '6', 7: '7', 8: '8', 9: '9', 10: 'T',
  11: 'J', 12: 'Q', 13: 'K', 14: 'A',
}

function encodeCard(c: Card): string {
  return `${RANK_CHAR[c.rank]}${c.suit}`
}

function encodeBoard(b: Board): string {
  return [...b.top, ...b.middle, ...b.bottom].map(encodeCard).join('')
}

console.error('Generating bonus opponent sample boards...\n')

const out: Record<BonusQualifier, string[]> = { QQ: [], KK: [], AA_OR_TRIPS: [] }

for (const tier of TIERS) {
  const n = SAMPLE_COUNTS[tier]
  const t0 = Date.now()
  for (let i = 0; i < n; i++) {
    const seed = (rng() * 0x7fffffff) | 0
    const deck = new Deck(seed)
    const cards = deck.deal(bonusDealCount(tier))
    const solverSeed = (rng() * 0x7fffffff) | 0
    const board = solveBonusVsOpponents(cards, DISCARDS[tier], [], mulberry32(solverSeed))
    out[tier].push(encodeBoard(board))
    if ((i + 1) % 100 === 0) console.error(`    ${tier} ${i + 1}/${n}`)
  }
  const elapsed = ((Date.now() - t0) / 1000).toFixed(1)
  console.error(`  ${tier.padEnd(11)} n=${n}  (${elapsed}s)`)
}

console.log('// Auto-generated by scripts/compute-bonus-samples.ts — do not hand-edit.')
console.log('import type { BonusQualifier } from \'./types\'')
console.log()
console.log('// Each string is 13 two-char card codes: 3 top + 5 middle + 5 bottom.')
console.log('export const BONUS_OPPONENT_SAMPLES: Record<BonusQualifier, readonly string[]> = {')
for (const tier of TIERS) {
  console.log(`  ${tier}: [`)
  for (const s of out[tier]) console.log(`    '${s}',`)
  console.log('  ],')
}
console.log('}')
