#!/usr/bin/env tsx
// Generates a fixed set of realistic side-game final boards, for embedding
// as static data (src/engine/sideGameSamplesData.ts). Run with:
//   npx tsx scripts/compute-side-game-samples.ts > /tmp/side-game-samples-out.txt
//
// Completes the "opponent field" the kicker-aware bonus solver
// (bonusOpponentScoring.ts) compares tied candidates against — bonus-eligible
// opponents were already covered by compute-bonus-samples.ts, but a real
// bonus round is also scored pairwise against non-qualifying side-game
// opponents, and no sample pool existed for "what does a typical side-game
// final board look like" until now.
//
// Reuses compute-bonus-ev.ts's playSideGame methodology unchanged (solo
// heuristic play, no opponent-awareness) — this is the same "BASE" opponent
// model already baked into the shipped BONUS_NET table, so this pool stays
// consistent with it rather than introducing a different side-game policy.

import { heuristicPlacement } from '../src/engine/heuristic'
import { applyPlacement } from '../src/engine/placement'
import { Deck } from '../src/engine/deck'
import type { Board, PartialBoard, Card } from '../src/engine/types'

function mulberry32(seed: number): () => number {
  let s = seed >>> 0
  return () => {
    s = (s + 0x6D2B79F5) >>> 0
    let t = s
    t = Math.imul(t ^ (t >>> 15), t | 1)
    t = (t ^ (t + Math.imul(t ^ (t >>> 7), t | 61))) >>> 0
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

const rng = mulberry32(20260824)
const SAMPLE_COUNT = 1000

function playSideGame(deck: Deck): Board {
  let board: PartialBoard = { top: [], middle: [], bottom: [] }
  const streetSizes = [5, 3, 3, 3, 3]
  for (let s = 0; s <= 4; s++) {
    const hand = deck.deal(streetSizes[s]!)
    const pl = heuristicPlacement(board, hand, s)
    board = applyPlacement(board, pl)
  }
  return board as Board
}

const RANK_CHAR: Record<number, string> = {
  2: '2', 3: '3', 4: '4', 5: '5', 6: '6', 7: '7', 8: '8', 9: '9', 10: 'T',
  11: 'J', 12: 'Q', 13: 'K', 14: 'A',
}
function encodeCard(c: Card): string {
  return `${RANK_CHAR[c.rank]}${c.suit}`
}
function encodeBoard(b: Board): string {
  return [...b.top, ...b.middle, ...b.bottom].map(encodeCard).join('')
}

console.error('Generating side-game sample boards...\n')

const t0 = Date.now()
const out: string[] = []
for (let i = 0; i < SAMPLE_COUNT; i++) {
  const seed = (rng() * 0x7fffffff) | 0
  const deck = new Deck(seed)
  out.push(encodeBoard(playSideGame(deck)))
}
const elapsed = ((Date.now() - t0) / 1000).toFixed(1)
console.error(`  n=${SAMPLE_COUNT}  (${elapsed}s)`)

console.log('// Auto-generated by scripts/compute-side-game-samples.ts — do not hand-edit.')
console.log()
console.log('// Each string is 13 two-char card codes: 3 top + 5 middle + 5 bottom.')
console.log('export const SIDE_GAME_SAMPLES: readonly string[] = [')
for (const s of out) console.log(`  '${s}',`)
console.log(']')
