#!/usr/bin/env python3
"""
Value network trainer for Hiinakas OFC.

Reads binary training data (OFCD format) generated by scripts/selfplay.ts,
trains a MLP to predict the expected net score from a board state, and
exports the weights in OFCW format for use by the browser engine worker.

Usage:
    python scripts/train.py [--data data/] [--out models/policy.bin] \
        [--epochs 20] [--lr 1e-3] [--batch 512] [--hidden 256 256 128]

Architecture:  525 → 256 → ReLU → 256 → ReLU → 128 → ReLU → 1 (linear)
Loss:          MSE on final game net score
"""

import argparse
import glob
import os
import struct
import sys
import time

import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset

ENCODE_DIM = 525
MAGIC_DATA  = b'OFCD'
MAGIC_MODEL = b'OFCW'

# ── Data loading ──────────────────────────────────────────────────────────────

def load_bin_file(path: str) -> tuple[np.ndarray, np.ndarray]:
    """Load a single OFCD binary file. Returns (features, labels)."""
    with open(path, 'rb') as f:
        header = f.read(16)
    magic = header[:4]
    if magic != MAGIC_DATA:
        raise ValueError(f'Bad magic in {path}: {magic}')
    version, feat_dim, num_samples = struct.unpack_from('<III', header, 4)
    if version != 1:
        raise ValueError(f'Unsupported version {version}')
    if feat_dim != ENCODE_DIM:
        raise ValueError(f'Feature dim mismatch: {feat_dim} vs {ENCODE_DIM}')

    data = np.fromfile(path, dtype=np.float32, offset=16)
    data = data[:num_samples * (feat_dim + 1)].reshape(num_samples, feat_dim + 1)
    return data[:, :feat_dim], data[:, feat_dim]


def load_data(data_path: str, window: int = 0) -> tuple[np.ndarray, np.ndarray]:
    """Load .bin files from a directory (or a single file).
    window > 0: use only the most recent N files (sliding window for policy stability)."""
    if os.path.isdir(data_path):
        files = sorted(glob.glob(os.path.join(data_path, '*.bin')))
    else:
        files = [data_path]

    if not files:
        raise FileNotFoundError(f'No .bin files found in {data_path}')

    if window > 0:
        files = files[-window:]
        print(f'  Sliding window: using last {len(files)} batches')

    all_x, all_y = [], []
    for f in files:
        x, y = load_bin_file(f)
        all_x.append(x)
        all_y.append(y)
        print(f'  Loaded {len(x):,} samples from {os.path.basename(f)}')

    xs = np.concatenate(all_x, axis=0)
    ys = np.concatenate(all_y, axis=0)
    return xs, ys


# ── Model ──────────────────────────────────────────────────────────────────────

class ValueNet(nn.Module):
    def __init__(self, input_dim: int, hidden: list[int]):
        super().__init__()
        layers = []
        prev = input_dim
        for h in hidden:
            layers += [nn.Linear(prev, h), nn.ReLU()]
            prev = h
        layers.append(nn.Linear(prev, 1))
        self.net = nn.Sequential(*layers)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x).squeeze(-1)


# ── Weight export (OFCW format) ───────────────────────────────────────────────

def export_weights(model: ValueNet, out_path: str, input_dim: int, hidden: list[int], y_scale: float) -> None:
    os.makedirs(os.path.dirname(out_path) or '.', exist_ok=True)
    layers_dims = list(zip([input_dim] + hidden, hidden + [1]))
    activations = [0] * len(hidden) + [1]  # relu × hidden, linear × output

    with open(out_path, 'wb') as f:
        # Header (v2: adds output_scale f32 after input_dim)
        f.write(MAGIC_MODEL)
        f.write(struct.pack('<III', 2, len(layers_dims), input_dim))
        f.write(struct.pack('<f', y_scale))

        linear_layers = [m for m in model.modules() if isinstance(m, nn.Linear)]
        for lin, (in_s, out_s), act in zip(linear_layers, layers_dims, activations):
            w = lin.weight.detach().cpu().numpy().astype(np.float32)  # [out × in]
            b = lin.bias.detach().cpu().numpy().astype(np.float32)    # [out]
            f.write(struct.pack('<III', in_s, out_s, act))
            f.write(w.tobytes())
            f.write(b.tobytes())

    size_kb = os.path.getsize(out_path) / 1024
    print(f'Exported weights → {out_path}  ({size_kb:.1f} KB)')


# ── Training ───────────────────────────────────────────────────────────────────

def load_ofcw_weights(path: str, model: 'ValueNet') -> None:
    """Load weights from OFCW binary format into a PyTorch model (for warm-starting)."""
    with open(path, 'rb') as f:
        data = f.read()
    magic = data[:4]
    if magic != MAGIC_MODEL:
        raise ValueError(f'Bad magic: {magic}')
    version, num_layers, file_input_dim = struct.unpack_from('<III', data, 4)
    if version not in (1, 2):
        raise ValueError(f'Unsupported version {version}')
    if file_input_dim != ENCODE_DIM:
        raise ValueError(f'Model input dim {file_input_dim} ≠ expected {ENCODE_DIM} — cannot warm-start, training from scratch')
    off = 16 + (4 if version >= 2 else 0)  # skip output_scale field in v2
    linear_layers = [m for m in model.modules() if isinstance(m, nn.Linear)]
    for lin in linear_layers:
        in_s, out_s, _ = struct.unpack_from('<III', data, off); off += 12
        w = np.frombuffer(data, dtype=np.float32, count=out_s * in_s, offset=off)
        off += out_s * in_s * 4
        b = np.frombuffer(data, dtype=np.float32, count=out_s, offset=off)
        off += out_s * 4
        lin.weight.data = torch.from_numpy(w.reshape(out_s, in_s).copy())
        lin.bias.data   = torch.from_numpy(b.copy())


def train(args: argparse.Namespace) -> None:
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f'Device: {device}')

    print('Loading data…')
    x_np, y_np = load_data(args.data, window=args.window)
    print(f'Total: {len(x_np):,} samples  (label range [{y_np.min():.1f}, {y_np.max():.1f}])')

    # Normalise labels to roughly [-1, 1] for stable training.
    y_scale = float(np.abs(y_np).max()) or 1.0
    y_np_norm = y_np / y_scale

    x = torch.from_numpy(x_np).to(device)
    y = torch.from_numpy(y_np_norm).to(device)

    n_val = max(1, int(0.05 * len(x)))
    idx = torch.randperm(len(x))
    val_idx, trn_idx = idx[:n_val], idx[n_val:]

    train_ds = TensorDataset(x[trn_idx], y[trn_idx])
    val_ds   = TensorDataset(x[val_idx], y[val_idx])
    train_dl = DataLoader(train_ds, batch_size=args.batch, shuffle=True,  num_workers=0)
    val_dl   = DataLoader(val_ds,   batch_size=args.batch, shuffle=False, num_workers=0)

    hidden = [int(h) for h in args.hidden]
    model  = ValueNet(ENCODE_DIM, hidden).to(device)

    # Warm-start from an existing model if --resume is given (iterative self-play).
    if args.resume and os.path.exists(args.resume):
        try:
            load_ofcw_weights(args.resume, model)
            print(f'Warm-starting from {args.resume}')
            # Use a lower LR when fine-tuning an existing model.
            args.lr = args.lr * 0.3
        except Exception as e:
            print(f'Warning: could not load resume weights ({e}), training from scratch')

    n_params = sum(p.numel() for p in model.parameters())
    print(f'Model: {ENCODE_DIM} → {" → ".join(str(h) for h in hidden)} → 1  ({n_params:,} params)  lr={args.lr:.2e}')

    opt = torch.optim.Adam(model.parameters(), lr=args.lr)
    sched = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=args.epochs)
    loss_fn = nn.MSELoss()

    best_val = float('inf')
    for epoch in range(1, args.epochs + 1):
        t0 = time.time()
        model.train()
        trn_loss = 0.0
        for xb, yb in train_dl:
            pred = model(xb)
            loss = loss_fn(pred, yb)
            opt.zero_grad()
            loss.backward()
            opt.step()
            trn_loss += loss.item() * len(xb)
        trn_loss /= len(train_ds)

        model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for xb, yb in val_dl:
                val_loss += loss_fn(model(xb), yb).item() * len(xb)
        val_loss /= len(val_ds)
        sched.step()

        # Convert MSE back to score units (approx RMSE in raw game points)
        rmse = (val_loss ** 0.5) * y_scale
        marker = ' *' if val_loss < best_val else ''
        if val_loss < best_val:
            best_val = val_loss
            export_weights(model, args.out, ENCODE_DIM, hidden, y_scale)

        elapsed = time.time() - t0
        print(f'Epoch {epoch:3d}/{args.epochs}  trn {trn_loss:.4f}  val {val_loss:.4f}  '
              f'rmse≈{rmse:.2f}pts  {elapsed:.1f}s{marker}')

    print(f'\nBest val MSE: {best_val:.4f}  (RMSE ≈ {(best_val**0.5)*y_scale:.2f} pts)')
    print(f'Weights saved to {args.out}')
    print('\nNext step: upload and deploy the model weights:')
    print(f'  firebase storage:cp {args.out} gs://hiinakas-355.firebasestorage.app/models/policy.bin')


# ── Entry point ────────────────────────────────────────────────────────────────

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Train OFC value network')
    parser.add_argument('--data',   default='data/',          help='Data dir or .bin file')
    parser.add_argument('--out',    default='models/policy.bin', help='Output weights path')
    parser.add_argument('--epochs', type=int,   default=20)
    parser.add_argument('--lr',     type=float, default=1e-3)
    parser.add_argument('--batch',  type=int,   default=512)
    parser.add_argument('--hidden', nargs='+', default=['256', '256', '128'],
                        help='Hidden layer sizes')
    parser.add_argument('--resume', default=None,
                        help='Path to existing OFCW weights to warm-start from (iterative self-play)')
    parser.add_argument('--window', type=int, default=0,
                        help='Use only the last N batch files (0=all). Prevents distribution shift from old policy data.')
    args = parser.parse_args()
    train(args)
